package com.agroflex.geo.service;

import com.agroflex.geo.model.Municipio;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Provee la lista oficial de municipios del estado de Puebla (INEGI).
 * Datos estáticos — 217 municipios, sin dependencia de base de datos.
 */
@Service
public class MunicipioService {

    private static final List<Municipio> MUNICIPIOS_PUEBLA = List.of(
            new Municipio(1,   "Acajete",                          "Puebla"),
            new Municipio(2,   "Acateno",                          "Puebla"),
            new Municipio(3,   "Acatlán",                          "Puebla"),
            new Municipio(4,   "Acatzingo",                        "Puebla"),
            new Municipio(5,   "Acteopan",                         "Puebla"),
            new Municipio(6,   "Ahuacatlán",                       "Puebla"),
            new Municipio(7,   "Ahuatlán",                         "Puebla"),
            new Municipio(8,   "Ahuazotepec",                      "Puebla"),
            new Municipio(9,   "Ahuehuetitla",                     "Puebla"),
            new Municipio(10,  "Ajalpan",                          "Puebla"),
            new Municipio(11,  "Albino Zertuche",                  "Puebla"),
            new Municipio(12,  "Aljojuca",                         "Puebla"),
            new Municipio(13,  "Altepexi",                         "Puebla"),
            new Municipio(14,  "Amixtlán",                         "Puebla"),
            new Municipio(15,  "Amozoc",                           "Puebla"),
            new Municipio(16,  "Aquixtla",                         "Puebla"),
            new Municipio(17,  "Atempan",                          "Puebla"),
            new Municipio(18,  "Atexcal",                          "Puebla"),
            new Municipio(19,  "Atlixco",                          "Puebla"),
            new Municipio(20,  "Atoyatempan",                      "Puebla"),
            new Municipio(21,  "Atzala",                           "Puebla"),
            new Municipio(22,  "Atzitzihuacán",                    "Puebla"),
            new Municipio(23,  "Atzitzintla",                      "Puebla"),
            new Municipio(24,  "Axutla",                           "Puebla"),
            new Municipio(25,  "Ayotoxco de Guerrero",             "Puebla"),
            new Municipio(26,  "Calpan",                           "Puebla"),
            new Municipio(27,  "Caltepec",                         "Puebla"),
            new Municipio(28,  "Camocuautla",                      "Puebla"),
            new Municipio(29,  "Caxhuacan",                        "Puebla"),
            new Municipio(30,  "Coatepec",                         "Puebla"),
            new Municipio(31,  "Coatzingo",                        "Puebla"),
            new Municipio(32,  "Cohetzala",                        "Puebla"),
            new Municipio(33,  "Cohuecan",                         "Puebla"),
            new Municipio(34,  "Coronango",                        "Puebla"),
            new Municipio(35,  "Coxcatlán",                        "Puebla"),
            new Municipio(36,  "Coyomeapan",                       "Puebla"),
            new Municipio(37,  "Coyotepec",                        "Puebla"),
            new Municipio(38,  "Cuapiaxtla de Madero",             "Puebla"),
            new Municipio(39,  "Cuautempan",                       "Puebla"),
            new Municipio(40,  "Cuautinchán",                      "Puebla"),
            new Municipio(41,  "Cuautlancingo",                    "Puebla"),
            new Municipio(42,  "Cuayuca de Andrade",               "Puebla"),
            new Municipio(43,  "Cuetzalan del Progreso",           "Puebla"),
            new Municipio(44,  "Cuyoaco",                          "Puebla"),
            new Municipio(45,  "Chalchicomula de Sesma",           "Puebla"),
            new Municipio(46,  "Chapulco",                         "Puebla"),
            new Municipio(47,  "Chiautla",                         "Puebla"),
            new Municipio(48,  "Chiautzingo",                      "Puebla"),
            new Municipio(49,  "Chiconcuautla",                    "Puebla"),
            new Municipio(50,  "Chichiquila",                      "Puebla"),
            new Municipio(51,  "Chietla",                          "Puebla"),
            new Municipio(52,  "Chigmecatitlán",                   "Puebla"),
            new Municipio(53,  "Chignahuapan",                     "Puebla"),
            new Municipio(54,  "Chignautla",                       "Puebla"),
            new Municipio(55,  "Chila",                            "Puebla"),
            new Municipio(56,  "Chila de la Sal",                  "Puebla"),
            new Municipio(57,  "Honey",                            "Puebla"),
            new Municipio(58,  "Chilchotla",                       "Puebla"),
            new Municipio(59,  "Chinantla",                        "Puebla"),
            new Municipio(60,  "Domingo Arenas",                   "Puebla"),
            new Municipio(61,  "Eloxochitlán",                     "Puebla"),
            new Municipio(62,  "Epatlán",                          "Puebla"),
            new Municipio(63,  "Esperanza",                        "Puebla"),
            new Municipio(64,  "Francisco Z. Mena",                "Puebla"),
            new Municipio(65,  "General Felipe Ángeles",           "Puebla"),
            new Municipio(66,  "Guadalupe",                        "Puebla"),
            new Municipio(67,  "Guadalupe Victoria",               "Puebla"),
            new Municipio(68,  "Hermenegildo Galeana",             "Puebla"),
            new Municipio(69,  "Huaquechula",                      "Puebla"),
            new Municipio(70,  "Huatlatlauca",                     "Puebla"),
            new Municipio(71,  "Huauchinango",                     "Puebla"),
            new Municipio(72,  "Huehuetla",                        "Puebla"),
            new Municipio(73,  "Huehuetlán el Chico",              "Puebla"),
            new Municipio(74,  "Huehuetlán el Grande",             "Puebla"),
            new Municipio(75,  "Huejotzingo",                      "Puebla"),
            new Municipio(76,  "Hueyapan",                         "Puebla"),
            new Municipio(77,  "Hueytamalco",                      "Puebla"),
            new Municipio(78,  "Hueytlalpan",                      "Puebla"),
            new Municipio(79,  "Huitzilan de Serdán",              "Puebla"),
            new Municipio(80,  "Huitziltepec",                     "Puebla"),
            new Municipio(81,  "Ixcamilpa de Guerrero",            "Puebla"),
            new Municipio(82,  "Ixcaquixtla",                      "Puebla"),
            new Municipio(83,  "Ixtacamaxtitlán",                  "Puebla"),
            new Municipio(84,  "Ixtepec",                          "Puebla"),
            new Municipio(85,  "Izúcar de Matamoros",              "Puebla"),
            new Municipio(86,  "Jalpan",                           "Puebla"),
            new Municipio(87,  "Jolalpan",                         "Puebla"),
            new Municipio(88,  "Jonotla",                          "Puebla"),
            new Municipio(89,  "Jopala",                           "Puebla"),
            new Municipio(90,  "Juan C. Bonilla",                  "Puebla"),
            new Municipio(91,  "Juan Galindo",                     "Puebla"),
            new Municipio(92,  "Juan N. Méndez",                   "Puebla"),
            new Municipio(93,  "Lafragua",                         "Puebla"),
            new Municipio(94,  "Libres",                           "Puebla"),
            new Municipio(95,  "La Magdalena Tlatlauquitepec",     "Puebla"),
            new Municipio(96,  "Mazapiltepec de Juárez",           "Puebla"),
            new Municipio(97,  "Mixtla",                           "Puebla"),
            new Municipio(98,  "Molcaxac",                         "Puebla"),
            new Municipio(99,  "Cañada Morelos",                   "Puebla"),
            new Municipio(100, "Naupan",                           "Puebla"),
            new Municipio(101, "Nauzontla",                        "Puebla"),
            new Municipio(102, "Nealtican",                        "Puebla"),
            new Municipio(103, "Nicolás Bravo",                    "Puebla"),
            new Municipio(104, "Nopalucan",                        "Puebla"),
            new Municipio(105, "Ocotepec",                         "Puebla"),
            new Municipio(106, "Ocoyucan",                         "Puebla"),
            new Municipio(107, "Olintla",                          "Puebla"),
            new Municipio(108, "Oriental",                         "Puebla"),
            new Municipio(109, "Pahuatlán",                        "Puebla"),
            new Municipio(110, "Palmar de Bravo",                  "Puebla"),
            new Municipio(111, "Pantepec",                         "Puebla"),
            new Municipio(112, "Petlalcingo",                      "Puebla"),
            new Municipio(113, "Piaxtla",                          "Puebla"),
            new Municipio(114, "Puebla",                           "Puebla"),
            new Municipio(115, "Quecholac",                        "Puebla"),
            new Municipio(116, "Quimixtlán",                       "Puebla"),
            new Municipio(117, "Rafael Lara Grajales",             "Puebla"),
            new Municipio(118, "Los Reyes de Juárez",              "Puebla"),
            new Municipio(119, "San Andrés Cholula",               "Puebla"),
            new Municipio(120, "San Antonio Cañada",               "Puebla"),
            new Municipio(121, "San Diego la Mesa Tochimiltzingo", "Puebla"),
            new Municipio(122, "San Felipe Tepatlan",              "Puebla"),
            new Municipio(123, "San Gabriel Chilac",               "Puebla"),
            new Municipio(124, "San Gregorio Atzompa",             "Puebla"),
            new Municipio(125, "San Jerónimo Tecuanipan",          "Puebla"),
            new Municipio(126, "San Jerónimo Xayacatlán",          "Puebla"),
            new Municipio(127, "San José Chiapa",                  "Puebla"),
            new Municipio(128, "San José Miahuatlán",              "Puebla"),
            new Municipio(129, "San Juan Atenco",                  "Puebla"),
            new Municipio(130, "San Juan Atzompa",                 "Puebla"),
            new Municipio(131, "San Martín Texmelucan",            "Puebla"),
            new Municipio(132, "San Martín Totoltepec",            "Puebla"),
            new Municipio(133, "San Matías Tlalancaleca",          "Puebla"),
            new Municipio(134, "San Miguel Ixitlán",               "Puebla"),
            new Municipio(135, "San Miguel Xoxtla",                "Puebla"),
            new Municipio(136, "San Nicolás Buenos Aires",         "Puebla"),
            new Municipio(137, "San Nicolás de los Ranchos",       "Puebla"),
            new Municipio(138, "San Pablo Anicano",                "Puebla"),
            new Municipio(139, "San Pedro Cholula",                "Puebla"),
            new Municipio(140, "San Pedro Yeloixtlahuaca",         "Puebla"),
            new Municipio(141, "San Salvador el Seco",             "Puebla"),
            new Municipio(142, "San Salvador el Verde",            "Puebla"),
            new Municipio(143, "San Salvador Huixcolotla",         "Puebla"),
            new Municipio(144, "San Sebastián Tlacotepec",         "Puebla"),
            new Municipio(145, "Santa Catarina Tlaltempan",        "Puebla"),
            new Municipio(146, "Santa Inés Ahuatempan",            "Puebla"),
            new Municipio(147, "Santa Inés de Zaragoza",           "Puebla"),
            new Municipio(148, "Santo Tomás Hueyotlipan",          "Puebla"),
            new Municipio(149, "Soltepec",                         "Puebla"),
            new Municipio(150, "Tecali de Herrera",                "Puebla"),
            new Municipio(151, "Tecamachalco",                     "Puebla"),
            new Municipio(152, "Tecomatlán",                       "Puebla"),
            new Municipio(153, "Tehuacán",                         "Puebla"),
            new Municipio(154, "Tehuitzingo",                      "Puebla"),
            new Municipio(155, "Tenampulco",                       "Puebla"),
            new Municipio(156, "Teopantlán",                       "Puebla"),
            new Municipio(157, "Teotlalco",                        "Puebla"),
            new Municipio(158, "Tepanco de López",                 "Puebla"),
            new Municipio(159, "Tepango de Rodríguez",             "Puebla"),
            new Municipio(160, "Tepatlaxco de Hidalgo",            "Puebla"),
            new Municipio(161, "Tepeaca",                          "Puebla"),
            new Municipio(162, "Tepemaxalco",                      "Puebla"),
            new Municipio(163, "Tepeojuma",                        "Puebla"),
            new Municipio(164, "Tepetzintla",                      "Puebla"),
            new Municipio(165, "Tepexco",                          "Puebla"),
            new Municipio(166, "Tepexi de Rodríguez",              "Puebla"),
            new Municipio(167, "Tepeyahualco",                     "Puebla"),
            new Municipio(168, "Tepeyahualco de Cuauhtémoc",       "Puebla"),
            new Municipio(169, "Tetela de Ocampo",                 "Puebla"),
            new Municipio(170, "Teteles de Ávila Castillo",        "Puebla"),
            new Municipio(171, "Teziutlán",                        "Puebla"),
            new Municipio(172, "Tianguismanalco",                  "Puebla"),
            new Municipio(173, "Tilapa",                           "Puebla"),
            new Municipio(174, "Tlacotepec de Benito Juárez",      "Puebla"),
            new Municipio(175, "Tlacuilotepec",                    "Puebla"),
            new Municipio(176, "Tlachichuca",                      "Puebla"),
            new Municipio(177, "Tlahuapan",                        "Puebla"),
            new Municipio(178, "Tlaltenango",                      "Puebla"),
            new Municipio(179, "Tlanepantla",                      "Puebla"),
            new Municipio(180, "Tlaola",                           "Puebla"),
            new Municipio(181, "Tlapacoya",                        "Puebla"),
            new Municipio(182, "Tlapanalá",                        "Puebla"),
            new Municipio(183, "Tlatlauquitepec",                  "Puebla"),
            new Municipio(184, "Tlaxco",                           "Puebla"),
            new Municipio(185, "Tochimilco",                       "Puebla"),
            new Municipio(186, "Tochtepec",                        "Puebla"),
            new Municipio(187, "Totoltepec de Guerrero",           "Puebla"),
            new Municipio(188, "Tulcingo",                         "Puebla"),
            new Municipio(189, "Tuzamapan de Galeana",             "Puebla"),
            new Municipio(190, "Tzicatlacoyan",                    "Puebla"),
            new Municipio(191, "Venustiano Carranza",              "Puebla"),
            new Municipio(192, "Vicente Guerrero",                 "Puebla"),
            new Municipio(193, "Xayacatlán de Bravo",              "Puebla"),
            new Municipio(194, "Xicotepec",                        "Puebla"),
            new Municipio(195, "Xicotlán",                         "Puebla"),
            new Municipio(196, "Xiutetelco",                       "Puebla"),
            new Municipio(197, "Xochiapulco",                      "Puebla"),
            new Municipio(198, "Xochiltepec",                      "Puebla"),
            new Municipio(199, "Xochitlán de Vicente Suárez",      "Puebla"),
            new Municipio(200, "Xochitlán Todos Santos",           "Puebla"),
            new Municipio(201, "Yaonáhuac",                        "Puebla"),
            new Municipio(202, "Yehualtepec",                      "Puebla"),
            new Municipio(203, "Zacapala",                         "Puebla"),
            new Municipio(204, "Zacapoaxtla",                      "Puebla"),
            new Municipio(205, "Zacatlán",                         "Puebla"),
            new Municipio(206, "Zapotitlán",                       "Puebla"),
            new Municipio(207, "Zapotitlán de Méndez",             "Puebla"),
            new Municipio(208, "Zaragoza",                         "Puebla"),
            new Municipio(209, "Zautla",                           "Puebla"),
            new Municipio(210, "Zihuateutla",                      "Puebla"),
            new Municipio(211, "Zinacatepec",                      "Puebla"),
            new Municipio(212, "Zoquiapan",                        "Puebla"),
            new Municipio(213, "Zoquitlán",                        "Puebla")
    );

    /**
     * Devuelve todos los municipios de Puebla.
     */
    public List<Municipio> getMunicipiosPuebla() {
        return MUNICIPIOS_PUEBLA;
    }

    /**
     * Filtra municipios por texto (búsqueda parcial, sin distinción de mayúsculas).
     */
    public List<Municipio> buscar(String query) {
        if (query == null || query.isBlank()) return MUNICIPIOS_PUEBLA;
        String q = query.trim().toLowerCase();
        return MUNICIPIOS_PUEBLA.stream()
                .filter(m -> m.nombre().toLowerCase().contains(q))
                .toList();
    }
}
